defaults: &defaults
  apns:
    pem_file: apns.pem
    host: gateway.sandbox.push.apple.com
    port: 2195

development:
  <<: *defaults

test:
  <<: *defaults

production:
  apns:
    pem_file: apns-production.pem
    host: gateway.push.apple.com
    port: 2195
