development:
  adapter: postgresql
  encoding: unicode
  database: ijkh_development
  pool: 5
  username: ijkh
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ijkh_test
  pool: 5
  username: ijkh
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ijkh_production
  pool: 5
  username: ijkh
  password:
