development:
  host: www.izkh.ru
  port: 5432
  adapter: postgresql
  encoding: utf8
  database: ijkh_production
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: ijkh_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: ijkh_production
  pool: 5
  username: postgres
  password: postgres
