development:
  adapter: postgresql
  encoding: utf8
  database: ijkh_development
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: utf8
  database: ijkh_test
  pool: 5
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: utf8
  database: ijkh_production
  pool: 5
  username: postgres
  password: postgres
